import { Button, Space } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const StyledButton = styled(Button)`
  color: blue;
`;
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Space>
          <StyledButton type="primary" size="large">
            Click Me
          </StyledButton>
          <Button type="primary" size="large">
            Click Me
          </Button>
          <Button type="primary" size="large">
            Click Me
          </Button>
          <Button type="primary" size="large">
            Click Me
          </Button>
        </Space>
      </main>
    </div>
  );
};

export default Home;
